### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Trickster2038** [Trickster2038/BmstuBot#1]
Bot:
- [x] Connect Django 'media' with bot
- [x] Bot tables names
- [x] Refresh telegram username in DB
- [x] Bot+DB image indexing
- [ ] moderate only with photos
- [x] faculty ID from DB

Console:
- [x] Functions: add/delete/show moderator by nickname/id
- [x] custom SQL

Web:
- [ ] Adaptive design for base.html
- [ ] favicon
- [x] Only is_filled users display
- [x] Moderation
- [x] PersonT.detail( )
- [x] Forms restyling in Jquery
- [ ] Change password
- [ ] One image model

All:
- [ ] Cascade delete: delete from user, auth and friends in ACID style

> Bio is only bio, additional 'contacts' field or telegram only?
> Users subsets isolation
___
- [ ] ? Rating system ?
- [ ] ? Donations ?
- [ ] ? Blame moderators ?
- [ ] ? Karma ?
- [x] Locale
- [x] Auth check
- [x] Delete animation
